update machine vision exercise

diff --git a/scripts/RADI/Dockerfile.dependencies_humble b/scripts/RADI/Dockerfile.dependencies_humble
--- a/scripts/RADI/Dockerfile.dependencies_humble
+++ b/scripts/RADI/Dockerfile.dependencies_humble
@@ -99,7 +99,7 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
 	&& apt-get clean autoclean \
   && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*
 
-RUN wget https://xpra.org/xorg.conf \
+RUN curl -L -o xorg.conf https://xpra.org/xorg.conf || echo "Download failed" \
   && rm -rf /tmp/*
 
 # Install noVNC and websockify
@@ -204,6 +204,7 @@ RUN pip3 install \
         pycodestyle==2.8 \
         cmakelint \
         cpplint \
+        transforms3d \
         colcon-lcov-result \
         PySimpleGUI-4-foss
 
@@ -303,6 +304,9 @@ WORKDIR /home/dev_ws
 RUN apt-get update && apt-get install -y \
     libpcl-dev \
     ros-humble-pcl-ros \
+    ros-humble-gazebo-ros-pkgs \
+    ros-humble-gazebo-plugins \
+    ros-humble-tf-transformations \
     ros-humble-pcl-conversions && \
     rm -rf /var/lib/apt/lists/*
 
